name: Template
main: Junkdude\Class
version: 1.0.0
api: [3.0.0-ALPHA3]
#If you have commands then.. (Remove the hashtags (#))
#commands:
 #yourcommand:
  #description: "Your command description"
  #usage: "/command"
  #permission: "pluginname.command" (If you have)
  
